// app/lomba/[id]/page.tsx
import {
  getLombaById,
  getKategori,
  groupPendaftarForLomba,
  getJuaraByLomba,
  getJuaraReadiness,
  getPendaftarByLomba,
  type DisplaySection,
} from "@/lib/db";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getInitials } from "@/lib/format";
import { formatTanggalLomba, lombaTimeStatus, juaraLabel, publicKategoriName, type LombaTimeStatus } from "@/lib/format";
import { SECTION_ICON } from "@/lib/constants";

export const dynamic = "force-dynamic";
export const revalidate = 0;

// Public-facing status derived from lomba.status + lomba.phase + Juara readiness
// + per-kategori tanggal (time-based). 9 variants for warga.
type PublicStatus =
  | "coming-soon"   // draft
  | "berlangsung"   // aktif + phase=NULL OR time=today
  | "kualifikasi"   // aktif + phase='kualifikasi' (picking finalists)
  | "final"         // aktif + phase='final' (picking Juara 1/2/3, partial)
  | "juara-terpilih"// allReady Juara (akhirnya atau sebelum Selesaikan)
  | "selesai"       // admin marked Selesai
  | "akan-datang"   // time=future (tanggal belum tiba)
  | "lewat-jadwal"  // time=past (semua tanggal udah lewat, admin belum Selesai)
  | "belum-mulai";  // aktif + no tanggal + no pendaftar (neutral — buka, tapi belum ada yg daftar/jadwal)

export default async function LombaDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const idNum = Number(id);
  if (isNaN(idNum)) notFound();
  const l = await getLombaById(idNum);
  if (!l || l.status === "draft") notFound();

  // Parallelize: kats, groups, juara, readiness, pendaftar are all independent after `l`.
  // pendaftar is needed for the Finalis section (get full finalist data with umur/jk).
  const [kats, groups, juaraMap, readiness, allDisetujui] = await Promise.all([
    getKategori(),
    groupPendaftarForLomba(idNum),
    getJuaraByLomba(idNum),
    getJuaraReadiness(idNum),
    getPendaftarByLomba(idNum, "disetujui"),
  ]);
  const katMap = new Map(kats.map((k) => [k.id, k]));

  // Flatten pjByKategori into per-PJ entries (one row per PJ, multiple allowed per kategori).
  const pjEntries: Array<{ katId: string; pj: { nama: string; kontak: string | null } }> = [];
  for (const katId of (Array.isArray(l.kategoriEligible) ? l.kategoriEligible : [])) {
    const list = l.pjByKategori?.[katId] || [];
    for (const pj of list) {
      if (pj?.nama) pjEntries.push({ katId, pj });
    }
  }

  const totalPeserta = groups.sections.reduce((sum, s) => sum + s.peserta.length, 0);

  // Public-facing status badge. v4: phase + time-based status.
  // Time-based (akan-datang / sedang-berlangsung / lewat-jadwal) wins when
  // lomba.status = "aktif" so warga get a calendar-aware "what's happening
  // now" view. Admin clicks Selesai → status pins to "selesai".
  const totalJuara = Object.values(juaraMap).reduce((sum, arr) => sum + arr.length, 0);
  // Derive global phase from per-kategori tutup state
  const eligibleKategori = Array.isArray(l.kategoriEligible) ? l.kategoriEligible : [];
  const tutupMap = l.kategoriTutupAt || {};
  const allKategoriTutup = eligibleKategori.length > 0 && eligibleKategori.every((kid) => !!tutupMap[kid]);
  const anyKategoriTutup = eligibleKategori.some((kid) => !!tutupMap[kid]);
  const hasPendaftar = totalPeserta > 0;
  // v4: Juara 1+2 readiness
  const showJuaraTerpilih = readiness.allReady && totalJuara > 0;
  // Time-based status (only when lomba is active/draft, not Selesai)
  const timeStatus: LombaTimeStatus =
    l.status === "aktif"
      ? lombaTimeStatus(l.jadwalByKategori, eligibleKategori)
      : "belum-dijadwalkan";
  const publicStatus: PublicStatus =
    l.status === "selesai"
      ? "selesai"
      : showJuaraTerpilih
      ? "juara-terpilih"
      : timeStatus === "akan-datang"
      ? "akan-datang"
      : timeStatus === "sedang-berlangsung"
      ? "berlangsung"
      : timeStatus === "lewat-jadwal"
      ? "lewat-jadwal"
      : allKategoriTutup
      ? "final"
      : anyKategoriTutup
      ? "final"  // some kategori in final phase
      : hasPendaftar && eligibleKategori.length > 0
      ? "kualifikasi"
      : "belum-mulai"; // fallback: aktif, no tanggal, no pendaftar

  // Finalis名单 — for each eligible kategori, collect finalists (is_finalist = 1).
  const finalisByKategori: Record<string, Array<{
    pendaftarId: number;
    nama: string;
    umur: number;
    jenisKelamin: "L" | "P";
    juaraRank: number | null; // 1, 2, 3 if Juara; null if just finalist
    kategoriId: string;        // original sub-kategori (k_anak_l / k_anak_p / k_balita / k_dewasa_p)
  }>> = {};

  // Map: pendaftarId → Juara rank (1, 2, 3 only) from getJuaraByLomba
  const juaraRankById = new Map<number, number>();
  for (const arr of Object.values(juaraMap)) {
    for (const j of arr) juaraRankById.set(j.pendaftarId, j.juaraRank);
  }

  for (const katId of eligibleKategori) {
    const finalists = allDisetujui
      .filter((p) => p.kategoriId === katId && p.isFinalist === 1)
      .map((p) => ({
        pendaftarId: p.id,
        nama: p.nama,
        umur: p.umur,
        jenisKelamin: p.jenisKelamin,
        juaraRank: juaraRankById.get(p.id) ?? null,
        // Track original sub-kategori so the public juaraLabel call
        // (which still uses kategoriId for the optional admin suffix)
        // has the right context. On public we pass forPublic=true so
        // the gender suffix is dropped regardless of this value.
        kategoriId: katId,
      }))
      // Sort: Juara 1/2/3 first (by rank ASC), then non-Juara finalists by umur ASC
      .sort((a, b) => {
        const aIsJuara = a.juaraRank !== null ? 0 : 1;
        const bIsJuara = b.juaraRank !== null ? 0 : 1;
        if (aIsJuara !== bIsJuara) return aIsJuara - bIsJuara;
        if (aIsJuara === 0 && bIsJuara === 0) return a.juaraRank! - b.juaraRank!;
        return a.umur - b.umur;
      });
    finalisByKategori[katId] = finalists;
  }

  // Total finalists across all kategori
  const totalFinalis = Object.values(finalisByKategori).reduce((sum, arr) => sum + arr.length, 0);
  // Show finalis section when: at least 1 kategori is Tutup (kualifikasi done for that kategori)
  // AND we have at least 1 finalist. Per spec: TIDAK tampil during full kualifikasi.
  const showFinalis = anyKategoriTutup && totalFinalis > 0;

  return (
    <div className="mobile-page">
      <div className="detail-hero">
        <Link href="/" className="absolute top-4 left-4 w-9 h-9 rounded-full bg-white/20 text-white flex items-center justify-center" aria-label="Kembali ke daftar lomba">
          <i className="fas fa-arrow-left"></i>
        </Link>
        <div className="detail-hero-content">
          <span className="text-6xl block mb-3">{l.emoji}</span>
          <h1 className="text-[22px] font-extrabold mb-1">{l.nama}</h1>
          <div className="flex flex-col items-center gap-3 mb-2">
            <span className="inline-block bg-white/20 px-3 py-1 rounded-full text-[11px] font-semibold">
              {/* Show per-kategori (k_anak_l + k_anak_p shown as separate
                  "Anak (Laki-laki)" / "Anak (Perempuan)") on the detail page
                  so Juara 1/2/3 for L and P can be distinguished. Home
                  page collapses to a single "Anak" via publicKategoriName. */}
              {l.kategoriEligible.map((k) => katMap.get(k)?.nama).filter(Boolean).join(" · ")}
            </span>
            <PublicStatusBadge status={publicStatus} />
          </div>
        </div>
      </div>

      <main className="app-content max-w-[1100px] mx-auto w-full">
        {l.deskripsi && (
          // Deskripsi callout — visually distinct from white info-sections
          // (Syarat/Jadwal/PJ). Soft pink gradient + decorative quote icon
          // + "Tentang Lomba" eyebrow label so warga won't skip it.
          <div className="relative mb-5 p-4 sm:p-5 rounded-2xl border border-[#FCE0E0] bg-gradient-to-br from-[#FCE0E0]/60 via-[#FDF5F5] to-white shadow-sm overflow-hidden">
            <i className="fas fa-quote-left absolute top-3 right-4 text-2xl text-primary opacity-20" aria-hidden="true"></i>
            <div className="text-[10px] font-bold text-primary uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <i className="fas fa-book-open text-[10px]"></i> Tentang Lomba
            </div>
            <p className="text-[14px] text-[#1F2937] leading-relaxed break-words relative z-[1]">
              {l.deskripsi}
            </p>
          </div>
        )}

        <div className="detail-2col grid grid-cols-1 lg:grid-cols-2 gap-3.5">
          <div className="space-y-3.5">
            <div className="info-section">
              <h3 className="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
                <i className="fas fa-clipboard-list text-primary"></i> Syarat & Ketentuan
              </h3>
              <ul className="space-y-2.5 text-[13px] text-[#6B7280] list-none p-0 leading-relaxed">
                {(l.syarat || []).map((s, i) => (
                  <li key={i} className="pl-5 relative">
                    <span className="absolute left-0 text-[#15803D] font-bold">✓</span> {s}
                  </li>
                ))}
              </ul>
            </div>

            <div className="info-section">
              <h3 className="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
                <i className="far fa-calendar text-primary"></i> Jadwal Pelaksanaan
              </h3>
              {(() => {
                const jadwals = (Array.isArray(l.kategoriEligible) ? l.kategoriEligible : [])
                  .map((kid) => ({ kid, jadwal: l.jadwalByKategori?.[kid] }))
                  .filter((x) => x.jadwal && (x.jadwal.tanggal != null || x.jadwal.jam != null));
                if (jadwals.length === 0) {
                  return <div className="text-center py-3 text-[#6B7280] text-sm">Belum ada jadwal yang diumumkan</div>;
                }
                return (
                  <div className="space-y-2.5 mt-2">
                    {jadwals.map(({ kid, jadwal }) => {
                      const kat = katMap.get(kid);
                      return (
                        <div key={kid} className="flex items-center gap-3 p-3 bg-[#F9FAFB] rounded-lg">
                          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent text-white flex items-center justify-center flex-shrink-0">
                            <i className="far fa-calendar text-base"></i>
                          </div>
                          <div className="flex-1 min-w-0 flex flex-col gap-0.5 leading-snug">
                            {kat && <div className="text-[10px] font-bold text-primary uppercase tracking-wide">{kat.nama}</div>}
                            {jadwal!.tanggal != null && (
                              <div className="font-semibold text-[13px]">{formatTanggalLomba(jadwal!.tanggal as number, "weekday-long")}</div>
                            )}
                            {jadwal!.jam && <div className="text-[11px] text-[#6B7280]">Pukul {jadwal!.jam} WIB</div>}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                );
              })()}
            </div>
          </div>

          <div className="info-section">
            <h3 className="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
              <i className="fas fa-user-tie text-primary"></i> Penanggung Jawab
              {(() => {
                const katCount = new Set(pjEntries.map((e) => e.katId)).size;
                return katCount > 1 ? (
                  <span className="text-[10px] font-normal text-[#6B7280]">per kategori</span>
                ) : null;
              })()}
            </h3>
            <div className="space-y-3 mt-2">
              {(() => {
                // Group PJ entries by PUBLIC name so k_anak_l + k_anak_p
                // collapse into a single "Anak" section (same PJs handle
                // both genders — showing 2 lists of identical names is
                // redundant for warga). Juara 1/2/3 distinction is
                // preserved on the Finalis section (separate L/P blocks
                // there). PJs are deduplicated by nama within a group.
                type PjGroup = {
                  publicName: string;
                  sampleKat: ReturnType<typeof katMap.get>;
                  pjs: Array<{ nama: string; kontak: string | null }>;
                };
                const seen = new Map<string, PjGroup>();
                const ordered: PjGroup[] = [];
                for (const kid of (Array.isArray(l.kategoriEligible) ? l.kategoriEligible : [])) {
                  const kat = katMap.get(kid);
                  if (!kat) continue;
                  const pjs = pjEntries.filter((e) => e.katId === kid).map((e) => e.pj);
                  if (pjs.length === 0) continue;
                  const publicName = publicKategoriName(kid);
                  let group = seen.get(publicName);
                  if (!group) {
                    group = { publicName, sampleKat: kat, pjs: [] };
                    seen.set(publicName, group);
                    ordered.push(group);
                  }
                  // Use sampleKat from the first encountered kid (L or P)
                  // — colors are usually identical or close enough; user
                  // only sees a single combined block.
                  for (const pj of pjs) {
                    if (!group.pjs.some((p) => p.nama === pj.nama)) {
                      group.pjs.push(pj);
                    }
                  }
                }
                if (ordered.length === 0) {
                  return (
                    <div className="text-center py-4 text-[#6B7280] text-sm">
                      Belum ada PJ yang ditugaskan
                    </div>
                  );
                }
                return ordered.map((g) => (
                  <div key={g.publicName} className="border border-[#E5E7EB] rounded-lg overflow-hidden">
                    <div
                      className="px-3.5 py-2 text-[11px] font-bold text-primary uppercase tracking-wide"
                      style={{
                        background: g.sampleKat?.colorBg || "#F9FAFB",
                        color: g.sampleKat?.colorText || "#92400E",
                        borderBottom: `1px solid ${g.sampleKat?.colorBorder || "#E5E7EB"}`,
                      }}
                    >
                      <i className="fas fa-tag"></i> {g.publicName}
                      <span className="ml-2 text-[10px] font-normal opacity-80 normal-case">{g.pjs.length} PJ</span>
                    </div>
                    <div className="divide-y divide-[#F3F4F6]">
                      {g.pjs.map((pj, pjIdx) => (
                        <div key={pjIdx} className="flex items-center gap-3 p-3 bg-white">
                          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent text-white flex items-center justify-center font-bold text-sm flex-shrink-0">
                            {getInitials(pj.nama)}
                          </div>
                          <div className="flex-1 min-w-0 flex flex-col gap-0.5 leading-snug">
                            <div className="font-semibold text-[13px] truncate">{pj.nama}</div>
                            {pj.kontak && <div className="text-[11px] text-[#6B7280]">{pj.kontak}</div>}
                          </div>
                          {pj.kontak && (
                            <a
                              href={`https://wa.me/${pj.kontak.replace(/\D/g, "")}`}
                              target="_blank"
                              rel="noreferrer"
                              className="flex-shrink-0 inline-flex items-center gap-1.5 px-3 py-2 bg-[#25D366] text-white rounded-lg text-[12px] font-bold hover:bg-[#1ebe57] transition-all no-underline"
                              title={`Chat WhatsApp ${pj.nama}`}
                            >
                              <i className="fab fa-whatsapp text-base"></i>
                              <span>Chat</span>
                            </a>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                ));
              })()}
            </div>
          </div>
        </div>

        {/* Finalis section — shows during final phase and after selesai.
            Per-kategori blocks so k_anak_l + k_anak_p show as separate
            "Anak (Laki-laki)" / "Anak (Perempuan)" sections, each with its
            own Juara 1/2/3 (with gender suffix for clarity). Other finalists
            get plain "Finalis" label. */}
        {showFinalis && (
          <div className="info-section mt-3.5">
            <h3 className="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
              <i className="fas fa-trophy text-[#FFD700]"></i> Finalis
              <span className="ml-auto text-[11px] font-normal text-[#6B7280]">
                {totalFinalis} orang
              </span>
            </h3>
            <div className="space-y-3">
              {Array.isArray(l.kategoriEligible) ? l.kategoriEligible.map((kid) => {
                const finalists = finalisByKategori[kid] || [];
                if (finalists.length === 0) return null;
                const kat = katMap.get(kid);
                return (
                  <div key={kid} className="juara-public-block">
                    <div className="juara-public-header" style={{ borderLeftColor: kat?.colorBorder || "#E11D1D" }}>
                      {kat?.nama || kid}
                    </div>
                    <div className="juara-public-list">
                      {finalists.map((f) => {
                        // Determine if this finalist is also a Juara (rank 1, 2, or 3)
                        const isJuara = f.juaraRank !== null && f.juaraRank <= 3;
                        const rowClass = isJuara ? `juara-public-row rank-${f.juaraRank}` : "juara-public-row";
                        return (
                          <div key={f.pendaftarId} className={rowClass}>
                            <span className="juara-medal-icon">
                              {isJuara
                                ? (f.juaraRank === 1 ? "🥇" : f.juaraRank === 2 ? "🥈" : "🥉")
                                : "👥"}
                            </span>
                            <div className="flex-1 min-w-0">
                              <div className="juara-public-nama">{f.nama}</div>
                              <div className="juara-public-meta">
                                {f.jenisKelamin === "L" ? "♂ Laki-laki" : "♀ Perempuan"} · {f.umur} tahun
                              </div>
                            </div>
                            {isJuara ? (
                              <span className={`juara-public-label rank-${f.juaraRank}`}>
                                {/* forPublic=false → gender suffix ("Juara 1 (Laki-laki)" /
                                    "Juara 1 (Perempuan)"). Detail page needs the
                                    distinction so warga can see L vs P winners
                                    explicitly. Home + success pages use
                                    publicKategoriName() to collapse instead. */}
                                {juaraLabel(kid, f.juaraRank as 1 | 2 | 3, false)}
                              </span>
                            ) : (
                              <span className="juara-public-label" style={{ background: "#F3F4F6", color: "#6B7280" }}>
                                Finalis
                              </span>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                );
              }) : null}
            </div>
          </div>
        )}

        {/* Peserta Terdaftar — per-kategori sections (Balita, Anak Laki-laki,
            Anak Perempuan, Dewasa) so Juara 1/2/3 for each can be
            distinguished. The sections come from the master kategori table
            via groupPendaftarForLomba (key: balita/anakL/anakP/dewasa). */}
        <div className="info-section mt-3.5">
          <h3 className="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
            <i className="fas fa-users text-primary"></i> Peserta Terdaftar
            <span className="ml-auto text-[11px] font-normal text-[#6B7280]">{totalPeserta} orang</span>
          </h3>

          {totalPeserta === 0 ? (
            <div className="text-center py-8 text-[#6B7280] text-sm bg-[#F9FAFB] rounded-lg">
              <i className="fas fa-user-slash text-2xl mb-2 block text-[#D1D5DB]"></i>
              Belum ada peserta yang terdaftar.
            </div>
          ) : (
            <div className="space-y-4">
              {groups.sections.map((sec) => (
                <PesertaTable
                  key={sec.key}
                  title={sec.title}
                  icon={SECTION_ICON[sec.key]}
                  ageRange={sec.rangeLabel}
                  color={sec.key}
                  data={sec.peserta}
                />
              ))}
            </div>
          )}
        </div>
      </main>

      {/* CTA — only for aktif lomba, and only when admin hasn't closed registration */}
      {l.status === "aktif" && l.pendaftaranDibuka && (
        <div className="sticky-cta-wrap">
          <div className="sticky-cta-inner max-w-[1100px] mx-auto">
            <Link href={`/lomba/${l.id}/daftar`} className="btn btn-primary btn-block">
              <i className="fas fa-pen-to-square"></i> Daftar Sekarang
            </Link>
          </div>
        </div>
      )}
      {/* Show "Pendaftaran Ditutup" notice instead of CTA when admin closed it */}
      {l.status === "aktif" && !l.pendaftaranDibuka && (
        <div className="sticky-cta-wrap">
          <div className="sticky-cta-inner max-w-[1100px] mx-auto">
            <div className="bg-[#FEE2E2] text-[#991B1B] rounded-xl p-3 text-center text-[13px] font-semibold flex items-center justify-center gap-2">
              <i className="fas fa-lock"></i> Pendaftaran Ditutup oleh Panitia
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// =================== Public status badge ===================
// Derive from lomba.status + lomba.phase + Juara readiness. 6 variants for warga.
function PublicStatusBadge({ status }: { status: PublicStatus }) {
  const config: Record<PublicStatus, { label: string; icon: string; className: string }> = {
    "coming-soon": { label: "Coming Soon", icon: "fa-clock", className: "bg-white/20 text-white" },
    "berlangsung": { label: "Sedang Berlangsung", icon: "fa-circle-play", className: "bg-[#FBBF24] text-[#92400E]" },
    "kualifikasi": { label: "Tahap Kualifikasi", icon: "fa-filter", className: "bg-[#FBBF24] text-[#92400E]" },
    "final": { label: "Tahap Final", icon: "fa-star", className: "bg-[#F97316] text-white" },
    "juara-terpilih": { label: "Juara Terpilih!", icon: "fa-trophy", className: "bg-[#3B82F6] text-white" },
    "selesai": { label: "Selesai", icon: "fa-check-circle", className: "bg-[#22C55E] text-white" },
    "akan-datang": { label: "Akan Datang", icon: "fa-calendar-plus", className: "bg-[#8B5CF6] text-white" },
    "lewat-jadwal": { label: "Lewat Jadwal", icon: "fa-calendar-xmark", className: "bg-[#6B7280] text-white" },
    "belum-mulai": { label: "Belum Mulai", icon: "fa-circle-dot", className: "bg-white/30 text-white" },
  };
  const c = config[status];
  return (
    <span className={`public-status-badge ${c.className}`}>
      <i className={`fas ${c.icon}`}></i> {c.label}
    </span>
  );
}

// Section keys with matching tailwind color classes (combines bg/text/border)
const SECTION_COLOR_CLASS: Record<DisplaySection["key"], string> = {
  balita: "bg-[#FDF2F8] text-[#9D174D] border-[#FBCFE8]",
  anakL: "bg-[#EFF6FF] text-[#1E40AF] border-[#BFDBFE]",
  anakP: "bg-[#FDF2F8] text-[#9D174D] border-[#FBCFE8]",
  dewasa: "bg-[#FFFBEB] text-[#92400E] border-[#FDE68A]",
};

function PesertaTable({
  title,
  icon,
  ageRange,
  color,
  data,
}: {
  title: string;
  icon: string;
  ageRange: string;
  color: DisplaySection["key"];
  data: { nama: string; umur: number }[];
}) {
  return (
    <div className={`rounded-lg border ${SECTION_COLOR_CLASS[color]} overflow-hidden`}>
      <div className="px-3.5 py-2.5 flex items-center gap-2 text-[12px] font-bold">
        <i className={`fas ${icon}`}></i>
        <span>{title}</span>
        <span className="font-normal opacity-70">· {ageRange}</span>
        <span className="ml-auto bg-white/60 px-2 py-0.5 rounded-full text-[11px]">{data.length} orang</span>
      </div>
      <div className="bg-white">
        <table className="w-full border-collapse text-[13px]">
          <thead>
            <tr className="text-[10px] font-bold uppercase text-[#6B7280] bg-[#F9FAFB]">
              <th className="text-left p-2.5 pl-3.5 w-[40px]">No</th>
              <th className="text-left p-2.5">Nama</th>
              <th className="text-right p-2.5 pr-3.5 w-[70px]">Umur</th>
            </tr>
          </thead>
          <tbody>
            {data.map((p, i) => (
              <tr key={i} className="border-t border-[#F3F4F6]">
                <td className="p-2.5 pl-3.5 text-[#9CA3AF] font-mono">{i + 1}</td>
                <td className="p-2.5 font-semibold text-[#1F2937]">{p.nama}</td>
                <td className="p-2.5 pr-3.5 text-right">
                  <span className="inline-block bg-[#F3F4F6] px-2 py-0.5 rounded-full text-[11px] font-bold text-[#374151]">
                    {p.umur} th
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// pages/lomba/[id]/index.vue
<script setup lang="ts">
// Public lomba detail — Vue 3 port of app/lomba/[id]/page.tsx.
// Server-rendered via useFetch; client receives pre-shaped data.
import { getInitials, formatTanggalLomba, lombaTimeStatus, juaraLabel, displayKategoriName } from "~/utils/format";

// Convert hex to rgba — used to derive light tints for section backgrounds
// without mutating stored kategori colors. Solid colorBg in DB (e.g. k_anak_l
// = #E11D1D) would otherwise dominate the page; alpha 0.1 keeps the section
// visually grouped but text stays legible.
function hexToRgba(hex: string, alpha: number): string {
  const h = (hex || "#F3F4F6").replace("#", "");
  const r = parseInt(h.slice(0, 2), 16) || 0;
  const g = parseInt(h.slice(2, 4), 16) || 0;
  const b = parseInt(h.slice(4, 6), 16) || 0;
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

const route = useRoute();
const id = computed(() => Number(route.params.id));

const { data, error } = await useFetch<{
  lomba: any;
  kategori: Array<{ id: string; nama: string; icon?: string; colorBg?: string; colorText?: string; colorBorder?: string }>;
  sections: Array<{
    key: string;
    title: string;
    rangeLabel: string;
    peserta: Array<{ nama: string; umur: number; jenisKelamin: "L" | "P"; kategoriId: string }>;
  }>;
  finalisByKategori: Record<string, any[]>;
  pjEntries: Array<{ katId: string; pj: { nama: string; kontak: string | null } }>;
  totalPeserta: number;
  totalJuara: number;
  totalFinalis: number;
  readinessAllReady: boolean;
}>(() => `/api/public/lomba/${id.value}`, { credentials: "include" });

if (error.value) {
  throw createError({ statusCode: 404, statusMessage: "Lomba tidak ditemukan" });
}

useHead(() => ({
  title: data.value?.lomba?.nama ? `${data.value.lomba.nama} — Lomba Kampung` : "Lomba Kampung",
}));

const l = computed(() => data.value?.lomba);
const kats = computed(() => data.value?.kategori ?? []);
const sections = computed(() => data.value?.sections ?? []);
const finalisByKategori = computed(() => data.value?.finalisByKategori ?? {});
const pjEntries = computed(() => data.value?.pjEntries ?? []);
const katMap = computed(() => new Map(kats.value.map((k: any) => [k.id, k])));

const eligibleKategori = computed(() => Array.isArray(l.value?.kategoriEligible) ? l.value.kategoriEligible : []);
const kualMap = computed(() => l.value?.kategoriTutupAt?.kual || {});
const allKategoriTutup = computed(() => eligibleKategori.value.length > 0 && eligibleKategori.value.every((kid: string) => !!kualMap.value[kid]));
const anyKategoriTutup = computed(() => eligibleKategori.value.some((kid: string) => !!kualMap.value[kid]));
const showJuaraTerpilih = computed(() => data.value?.readinessAllReady && (data.value?.totalJuara ?? 0) > 0);
const timeStatus = computed(() =>
  l.value?.status === "aktif"
    ? lombaTimeStatus(l.value.jadwalByKategori, eligibleKategori.value)
    : "belum-dijadwalkan"
);
const publicStatus = computed(() => {
  if (l.value?.status === "selesai") return "selesai";
  if (showJuaraTerpilih.value) return "juara-terpilih";
  if (timeStatus.value === "akan-datang") return "akan-datang";
  if (timeStatus.value === "sedang-berlangsung") return "berlangsung";
  if (timeStatus.value === "lewat-jadwal") return "lewat-jadwal";
  if (allKategoriTutup.value || anyKategoriTutup.value) return "final";
  if (sections.value.length > 0 && eligibleKategori.value.length > 0) return "kualifikasi";
  return "belum-mulai";
});

const showFinalis = computed(() => anyKategoriTutup.value && (data.value?.totalFinalis ?? 0) > 0);

const STATUS_BADGES: Record<string, { label: string; bg: string; text: string; icon: string }> = {
  "coming-soon":    { label: "Coming Soon", bg: "#E5E7EB", text: "#374151", icon: "fa-clock" },
  "berlangsung":    { label: "Sedang Berlangsung", bg: "#FBBF24", text: "#92400E", icon: "fa-bolt" },
  "kualifikasi":    { label: "Tahap Kualifikasi", bg: "#FEF3C7", text: "#92400E", icon: "fa-hourglass-half" },
  "final":          { label: "Tahap Final", bg: "#DBEAFE", text: "#1E40AF", icon: "fa-trophy" },
  "juara-terpilih": { label: "Juara Terpilih", bg: "#DCFCE7", text: "#15803D", icon: "fa-crown" },
  "selesai":        { label: "Selesai", bg: "#1F2937", text: "#FFFFFF", icon: "fa-flag-checkered" },
  "akan-datang":    { label: "Akan Datang", bg: "#8B5CF6", text: "#FFFFFF", icon: "fa-calendar" },
  "lewat-jadwal":   { label: "Lewat Jadwal", bg: "#6B7280", text: "#FFFFFF", icon: "fa-calendar-xmark" },
  "belum-mulai":    { label: "Belum Mulai", bg: "#E5E7EB", text: "#374151", icon: "fa-circle-pause" },
};

// Group jadwal by public name
type JadwalGroup = { publicName: string; sampleKat?: any; jadwals: Array<{ tanggal: number; jam: string | null }> };
const jadwalGroups = computed<JadwalGroup[]>(() => {
  const seen = new Map<string, JadwalGroup>();
  const ordered: JadwalGroup[] = [];
  for (const kid of eligibleKategori.value) {
    const sampleKat = (katMap.value as any).get(kid);
    const publicName = displayKategoriName(kid, sampleKat);
    let g = seen.get(publicName);
    if (!g) {
      g = { publicName, sampleKat, jadwals: [] };
      seen.set(publicName, g);
      ordered.push(g);
    }
    const j = l.value?.jadwalByKategori?.[kid];
    if (j && j.tanggal != null) g.jadwals.push({ tanggal: j.tanggal, jam: j.jam });
  }
  return ordered;
});
const withJadwal = computed(() => jadwalGroups.value.filter((g) => g.jadwals.length > 0));

// =================== Sections enriched with jadwal ===================
// Each section (grouped by age range like "Anak Laki-laki") gets the
// earliest upcoming jadwal of its kategori, so the public can see WHEN
// that batch is competing.
type EnrichedPeserta = {
  nama: string;
  umur: number;
  jenisKelamin: "L" | "P";
  kategoriId: string;
  kategoriLabel: string;
  jadwalTanggal: number | null;
  jadwalJam: string | null;
};
type EnrichedSection = {
  key: string;
  title: string;
  rangeLabel: string;
  icon: string;
  colorBg: string;
  colorText: string;
  colorBorder: string;
  totalCount: number;
  // Earliest upcoming jadwal for this section (across all peserta)
  earliestJadwal: { tanggal: number; jam: string | null; publicName: string } | null;
  peserta: EnrichedPeserta[];
  // If section contains >1 kategori, show "multi" indicator
  isMultiKategori: boolean;
};
const sectionsEnriched = computed<EnrichedSection[]>(() => {
  const out: EnrichedSection[] = [];
  const now = Date.now();
  for (const sec of sections.value) {
    // Find distinct kategori labels + first jadwal across the section
    const katSet = new Set<string>();
    const enrichedPeserta: EnrichedPeserta[] = [];
    for (const p of sec.peserta) {
      katSet.add(p.kategoriId);
      const kat = (katMap.value as any).get(p.kategoriId);
      const j = l.value?.jadwalByKategori?.[p.kategoriId];
      enrichedPeserta.push({
        nama: p.nama,
        umur: p.umur,
        jenisKelamin: p.jenisKelamin,
        kategoriId: p.kategoriId,
        kategoriLabel: displayKategoriName(p.kategoriId, kat),
        jadwalTanggal: j?.tanggal ?? null,
        jadwalJam: j?.jam ?? null,
      });
    }
    // Pick the earliest FUTURE jadwal (or first jadwal if none future)
    const withJadwalArr = enrichedPeserta
      .filter((p) => p.jadwalTanggal != null)
      .sort((a, b) => (a.jadwalTanggal! - b.jadwalTanggal!));
    let earliest: EnrichedSection["earliestJadwal"] = null;
    for (const p of withJadwalArr) {
      const ts = p.jadwalTanggal! * 1000; // unix seconds → ms
      if (ts >= now - 86_400_000) { // include today
        const kat = (katMap.value as any).get(p.kategoriId);
        earliest = {
          tanggal: p.jadwalTanggal!,
          jam: p.jadwalJam ?? null,
          publicName: displayKategoriName(p.kategoriId, kat),
        };
        break;
      }
    }
    if (!earliest && withJadwalArr.length > 0) {
      // fall back to most recent past jadwal
      const p = withJadwalArr[withJadwalArr.length - 1];
      const kat = (katMap.value as any).get(p.kategoriId);
      earliest = {
        tanggal: p.jadwalTanggal!,
        jam: p.jadwalJam ?? null,
        publicName: displayKategoriName(p.kategoriId, kat),
      };
    }
    // Section visual style: use first kategori's colors
    const sampleKat = sec.peserta.length > 0
      ? (katMap.value as any).get(sec.peserta[0].kategoriId)
      : null;
    out.push({
      key: sec.key,
      title: sec.title,
      rangeLabel: sec.rangeLabel,
      icon: sampleKat?.icon || "fas fa-users",
      colorBg: sampleKat?.colorBg || "#FEF3C7",
      colorText: sampleKat?.colorText || "#92400E",
      colorBorder: sampleKat?.colorBorder || "#FDE68A",
      totalCount: sec.peserta.length,
      earliestJadwal: earliest,
      peserta: enrichedPeserta,
      isMultiKategori: katSet.size > 1,
    });
  }
  return out;
});

// Scroll to the registration CTA at the bottom of the page
function scrollToDaftar() {
  if (typeof document === "undefined") return;
  const target = document.getElementById("cta-daftar");
  if (target) {
    target.scrollIntoView({ behavior: "smooth", block: "center" });
  }
}

// Group PJ by public name
type PjGroup = { publicName: string; sampleKat?: any; pjs: Array<{ nama: string; kontak: string | null }> };
const pjGroups = computed<PjGroup[]>(() => {
  const seen = new Map<string, PjGroup>();
  const ordered: PjGroup[] = [];
  for (const kid of eligibleKategori.value) {
    const kat = (katMap.value as any).get(kid);
    if (!kat) continue;
    const pjs = pjEntries.value.filter((e) => e.katId === kid).map((e) => e.pj);
    if (pjs.length === 0) continue;
    const publicName = displayKategoriName(kid, kat);
    let group = seen.get(publicName);
    if (!group) {
      group = { publicName, sampleKat: kat, pjs: [] };
      seen.set(publicName, group);
      ordered.push(group);
    }
    for (const pj of pjs) {
      if (!group.pjs.some((p) => p.nama === pj.nama)) group.pjs.push(pj);
    }
  }
  return ordered;
});
</script>

<template>
  <div v-if="l" class="mobile-page">
    <!-- Festive hero -->
    <div class="detail-hero anim-fade-up">
      <NuxtLink to="/" class="absolute top-4 left-4 w-10 h-10 rounded-full bg-white/20 backdrop-blur text-white flex items-center justify-center hover:bg-white/30 transition-colors z-10" aria-label="Kembali ke daftar lomba">
        <i class="fas fa-arrow-left" />
      </NuxtLink>
      <div class="detail-hero-content">
        <div class="text-7xl mb-3 anim-float inline-block">{{ l.emoji }}</div>
        <h1 class="text-[24px] sm:text-[28px] font-extrabold mb-1 leading-tight drop-shadow-md">{{ l.nama }}</h1>
        <div class="flex flex-col items-center gap-2.5 mt-2">
          <span class="hero-pill">
            <i class="fas fa-tag" />
            {{ eligibleKategori.map((k: string) => (katMap.get(k) as any)?.nama).filter(Boolean).join(" · ") }}
          </span>
          <span
            v-if="l.faseEnabled"
            class="inline-flex items-center gap-1.5 bg-gradient-to-r from-[#1E40AF] via-[#92400E] to-[#7C3AED] px-3 py-1.5 rounded-full text-[11px] font-extrabold text-white shadow-lg"
            title="Lomba ini punya 3 fase: Kualifikasi → Semi Final → Final"
          >
            <i class="fas fa-sitemap" /> 3 Fase: Kualifikasi → Semi Final → Final
          </span>
          <span
            v-else
            class="inline-flex items-center gap-1.5 bg-white text-[#9D1010] px-3 py-1.5 rounded-full text-[11px] font-extrabold border border-[#E11D1D]/40 shadow-sm"
            title="Lomba ini punya 2 fase: Kualifikasi → Final"
          >
            <i class="fas fa-stream" /> 2 Fase: Kualifikasi → Final
          </span>
          <span
            v-if="STATUS_BADGES[publicStatus]"
            class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[11px] font-extrabold shadow"
            :style="{ background: STATUS_BADGES[publicStatus].bg, color: STATUS_BADGES[publicStatus].text }"
          >
            <i :class="['fas', STATUS_BADGES[publicStatus].icon]" /> {{ STATUS_BADGES[publicStatus].label }}
          </span>
        </div>
      </div>
    </div>

    <!-- Scroll hint: registration CTA is at the bottom of the page -->
    <div
      v-if="l.status === 'aktif' && l.pendaftaranDibuka !== false"
      class="text-center -mt-3 mb-2 anim-fade-up"
      style="animation-delay: 250ms"
    >
      <button
        type="button"
        @click="scrollToDaftar"
        class="inline-flex items-center gap-1.5 text-[12px] font-bold text-primary bg-white/95 backdrop-blur px-3.5 py-2 rounded-full border border-primary/30 shadow-md hover:bg-primary hover:text-white hover:border-primary transition-all no-underline cursor-pointer"
        aria-label="Scroll ke bawah untuk tombol pendaftaran"
      >
        <i class="fas fa-pen-to-square text-[11px]" />
        Scroll untuk mendaftar
        <i class="fas fa-arrow-down anim-float text-[11px]" style="animation-duration: 1.5s" />
      </button>
    </div>

    <main class="app-content max-w-[1100px] mx-auto w-full">
      <!-- Deskripsi -->
      <div v-if="l.deskripsi" class="relative mb-5 p-4 sm:p-5 rounded-2xl border border-[#FCE0E0] bg-gradient-to-br from-[#FCE0E0]/60 via-[#FDF5F5] to-white shadow-sm overflow-hidden">
        <i class="fas fa-quote-left absolute top-3 right-4 text-2xl text-primary opacity-20" aria-hidden="true" />
        <div class="text-[10px] font-bold text-primary uppercase tracking-wider mb-2 flex items-center gap-1.5">
          <i class="fas fa-book-open text-[10px]" /> Tentang Lomba
        </div>
        <p class="text-[14px] text-[#1F2937] leading-relaxed break-words relative z-[1]">{{ l.deskripsi }}</p>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-3.5">
        <!-- Left col -->
        <div class="space-y-3.5">
          <!-- Syarat -->
          <div class="info-section">
            <h3 class="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
              <i class="fas fa-clipboard-list text-primary" /> Syarat & Ketentuan
            </h3>
            <ul class="space-y-2.5 text-[13px] text-[#6B7280] list-none p-0 leading-relaxed">
              <li v-for="(s, i) in (l.syarat || [])" :key="i" class="pl-5 relative">
                <span class="absolute left-0 text-[#15803D] font-bold">✓</span> {{ s }}
              </li>
            </ul>
          </div>

          <!-- Jadwal -->
          <div class="info-section">
            <h3 class="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
              <i class="far fa-calendar text-primary" /> Jadwal Pelaksanaan
            </h3>
            <div v-if="withJadwal.length === 0" class="text-center py-3 text-[#6B7280] text-sm">
              Belum ada jadwal yang diumumkan
            </div>
            <div v-else class="space-y-2.5 mt-2">
              <div
                v-for="g in withJadwal"
                :key="g.publicName"
                class="flex items-center gap-3 p-3 bg-[#F9FAFB] rounded-lg"
              >
                <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent text-white flex items-center justify-center flex-shrink-0">
                  <i class="far fa-calendar text-base" />
                </div>
                <div class="flex-1 min-w-0 flex flex-col gap-0.5 leading-snug">
                  <div class="text-[10px] font-bold text-primary uppercase tracking-wide">{{ g.publicName }}</div>
                  <template v-if="g.jadwals.every((j) => j.tanggal === g.jadwals[0].tanggal)">
                    <div class="font-semibold text-[13px]">{{ formatTanggalLomba(g.jadwals[0].tanggal, "weekday-long") }}</div>
                  </template>
                  <template v-else>
                    <div class="font-semibold text-[13px] flex flex-col gap-0.5">
                      <span v-for="t in Array.from(new Set(g.jadwals.map((j) => j.tanggal)))" :key="t">{{ formatTanggalLomba(t, "weekday-long") }}</span>
                    </div>
                  </template>
                  <div v-if="Array.from(new Set(g.jadwals.map((j) => j.jam).filter((j): j is string => !!j))).length > 0" class="text-[11px] text-[#6B7280]">
                    Pukul {{ Array.from(new Set(g.jadwals.map((j) => j.jam).filter((j): j is string => !!j))).join(", ") }} WIB
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Right col: PJ -->
        <div class="info-section">
          <h3 class="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
            <i class="fas fa-user-tie text-primary" /> Penanggung Jawab
            <span v-if="new Set(pjEntries.map((e) => e.katId)).size > 1" class="text-[10px] font-normal text-[#6B7280]">per kategori</span>
          </h3>
          <div v-if="pjGroups.length === 0" class="text-center py-4 text-[#6B7280] text-sm">
            Belum ada PJ yang ditugaskan
          </div>
          <div v-else class="space-y-3 mt-2">
            <div v-for="g in pjGroups" :key="g.publicName" class="border border-[#E5E7EB] rounded-lg overflow-hidden">
              <div
                class="px-3.5 py-2 text-[11px] font-bold text-primary uppercase tracking-wide"
                :style="{
                  background: g.sampleKat?.colorBg || '#F9FAFB',
                  color: g.sampleKat?.colorText || '#92400E',
                  borderBottom: `1px solid ${g.sampleKat?.colorBorder || '#E5E7EB'}`,
                }"
              >
                <i class="fas fa-tag" /> {{ g.publicName }}
                <span class="ml-2 text-[10px] font-normal opacity-80 normal-case">{{ g.pjs.length }} PJ</span>
              </div>
              <div class="divide-y divide-[#F3F4F6]">
                <div v-for="(pj, pjIdx) in g.pjs" :key="pjIdx" class="flex items-center gap-3 p-3 bg-white">
                  <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent text-white flex items-center justify-center font-bold text-sm flex-shrink-0">
                    {{ getInitials(pj.nama) }}
                  </div>
                  <div class="flex-1 min-w-0 flex flex-col gap-0.5 leading-snug">
                    <div class="font-semibold text-[13px] truncate">{{ pj.nama }}</div>
                    <div v-if="pj.kontak" class="text-[11px] text-[#6B7280]">{{ pj.kontak }}</div>
                  </div>
                  <a
                    v-if="pj.kontak"
                    :href="`https://wa.me/${pj.kontak.replace(/\D/g, '')}`"
                    target="_blank"
                    rel="noreferrer"
                    class="flex-shrink-0 inline-flex items-center gap-1.5 px-3 py-2 bg-[#25D366] text-white rounded-lg text-[12px] font-bold hover:bg-[#1ebe57] transition-all no-underline"
                    :title="`Chat WhatsApp ${pj.nama}`"
                  >
                    <i class="fab fa-whatsapp" /> WA
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Peserta Terdaftar — grouped by kategori, enriched with jadwal slot -->
      <div v-if="sectionsEnriched.length > 0" class="info-section mt-3.5">
        <div class="flex items-center justify-between gap-2 mb-3">
          <h3 class="text-[13px] font-bold text-[#1F2937] flex items-center gap-2">
            <i class="fas fa-users text-primary" /> Peserta Terdaftar
          </h3>
          <span class="text-[10px] font-bold bg-[#FCE0E0] text-primary px-2.5 py-0.5 rounded-full inline-flex items-center gap-1">
            <i class="fas fa-check-circle text-[9px]" />
            {{ data?.totalPeserta }} disetujui
          </span>
        </div>

        <div class="space-y-2.5">
          <div
            v-for="sec in sectionsEnriched"
            :key="sec.key"
            class="rounded-2xl border-2 overflow-hidden shadow-sm transition-shadow hover:shadow-md"
            :style="{
              background: hexToRgba(sec.colorBg, 0.1),
              borderColor: hexToRgba(sec.colorText, 0.25),
              color: sec.colorText,
            }"
          >
            <!-- Section header: icon + title + count + earliest jadwal -->
            <div class="px-3 pt-2.5 pb-2.5 flex items-start gap-2.5">
              <div
                class="w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 bg-white/85 shadow-sm"
                :style="{ color: sec.colorText }"
              >
                <i class="fa text-[14px]" :class="sec.icon" />
              </div>
              <div class="flex-1 min-w-0 leading-snug">
                <div class="flex items-center gap-1.5 flex-wrap">
                  <h4 class="text-[13px] font-extrabold uppercase tracking-wide">{{ sec.title }}</h4>
                  <span class="text-[10px] font-semibold opacity-75">· {{ sec.rangeLabel }}</span>
                </div>
                <!-- Earliest upcoming jadwal pill -->
                <div v-if="sec.earliestJadwal" class="mt-1.5 flex items-center gap-1.5 flex-wrap">
                  <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-white/90 text-[10px] font-bold backdrop-blur-sm shadow-sm" :style="{ color: sec.colorText }">
                    <i class="far fa-calendar text-[10px]" />
                    {{ formatTanggalLomba(sec.earliestJadwal.tanggal, "weekday-long") }}
                    <template v-if="sec.earliestJadwal.jam">
                      <span class="opacity-60">·</span>
                      <i class="far fa-clock text-[10px]" />
                      {{ sec.earliestJadwal.jam }} WIB
                    </template>
                  </span>
                  <span v-if="sec.isMultiKategori" class="text-[9px] font-semibold opacity-70">multi-kategori</span>
                </div>
                <div v-else class="mt-1 text-[10px] opacity-70 italic">
                  <i class="far fa-calendar-plus text-[10px]" /> Jadwal menyusul
                </div>
              </div>
              <span class="text-[11px] font-extrabold bg-white px-2.5 py-1 rounded-full flex-shrink-0 shadow-sm inline-flex items-center gap-1" :style="{ color: sec.colorText }">
                <i class="fas fa-user-group text-[10px]" />
                {{ sec.totalCount }}
              </span>
            </div>

            <!-- Subtle divider between header and peserta list -->
            <div class="mx-3 border-t" :style="{ borderColor: hexToRgba(sec.colorText, 0.15) }" />

            <!-- Peserta grid: adaptive columns to avoid empty cells with low counts -->
            <div
              class="p-2.5 grid gap-2"
              :class="[
                sec.peserta.length === 1 ? 'grid-cols-1' :
                sec.peserta.length <= 3 ? 'grid-cols-2' :
                'grid-cols-2 sm:grid-cols-3',
              ]"
            >
              <div
                v-for="(p, i) in sec.peserta"
                :key="`${sec.key}-${i}`"
                class="flex items-center gap-2.5 px-2.5 py-2 rounded-xl bg-white shadow-sm border transition-all hover:shadow-md hover:-translate-y-0.5 active:translate-y-0"
                :style="{ borderColor: hexToRgba(sec.colorText, 0.2) }"
                :title="`${p.nama} (${p.umur} th)${p.jadwalJam ? ' · tanding ' + p.jadwalJam + ' WIB' : ''}`"
              >
                <div
                  class="w-9 h-9 rounded-full flex items-center justify-center font-extrabold text-[11px] flex-shrink-0 shadow-sm"
                  :style="{ background: sec.colorText, color: 'white' }"
                >
                  {{ getInitials(p.nama) }}
                </div>
                <div class="flex-1 min-w-0 leading-tight">
                  <div class="text-[13px] font-bold truncate" :style="{ color: sec.colorText }">{{ p.nama }}</div>
                  <div class="text-[10.5px] opacity-80 flex items-center gap-1 mt-0.5">
                    <i :class="['fas', p.jenisKelamin === 'L' ? 'fa-mars' : 'fa-venus']" class="text-[9px]" />
                    <span>{{ p.umur }} th</span>
                    <template v-if="p.jadwalJam">
                      <span class="opacity-50">·</span>
                      <i class="far fa-clock text-[9px]" />
                      <span>{{ p.jadwalJam }}</span>
                    </template>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Subtle hint at the bottom -->
        <p class="text-[10px] text-[#9CA3AF] text-center mt-3 italic">
          <i class="fas fa-info-circle" /> Hanya peserta <strong>disetujui</strong> yang tampil di sini. Pendaftaran & approval dilakukan oleh admin.
        </p>
      </div>

      <!-- Finalis + Juara (when shown) -->
      <div v-if="showFinalis" class="info-section mt-3.5">
        <h3 class="text-[13px] font-bold mb-3 text-[#1F2937] flex items-center gap-2">
          <i class="fas fa-medal text-primary" /> Finalis & Juara
        </h3>
        <div class="space-y-3">
          <div v-for="katId in eligibleKategori" :key="katId">
            <template v-if="finalisByKategori[katId] && finalisByKategori[katId].length > 0">
              <div class="text-[11px] font-bold text-[#6B7280] uppercase tracking-wide mb-1.5">
                {{ displayKategoriName(katId, katMap.get(katId)) }}
              </div>
              <div class="space-y-1.5">
                <div
                  v-for="f in finalisByKategori[katId]"
                  :key="f.pendaftarId"
                  class="flex items-center gap-2 p-2.5 rounded-lg"
                  :class="f.juaraRank === 1 ? 'bg-[#FFFBEB] border border-[#FDE68A]' : f.juaraRank === 2 ? 'bg-[#F9FAFB] border border-[#E5E7EB]' : f.juaraRank === 3 ? 'bg-[#FEF3C7] border border-[#FBBF24]' : 'bg-white border border-[#E5E7EB]'"
                >
                  <span
                    v-if="f.juaraRank"
                    :class="[
                      'text-[14px] font-extrabold w-9 h-9 flex items-center justify-center rounded-full flex-shrink-0',
                      f.juaraRank === 1 ? 'bg-gradient-to-br from-[#FFD700] to-[#FFA500] text-white' : f.juaraRank === 2 ? 'bg-gradient-to-br from-[#C0C0C0] to-[#808080] text-white' : 'bg-gradient-to-br from-[#CD7F32] to-[#8B4513] text-white',
                    ]"
                  >
                    {{ f.juaraRank }}
                  </span>
                  <span v-else class="text-[10px] font-bold text-[#6B7280] bg-[#F3F4F6] w-9 h-9 flex items-center justify-center rounded-full flex-shrink-0">F</span>
                  <div class="flex-1 min-w-0">
                    <div class="text-[13px] font-semibold text-[#1F2937] truncate">{{ f.nama }}</div>
                    <div class="text-[10px] text-[#6B7280]">{{ f.umur }} th · {{ f.jenisKelamin === "L" ? "Laki-laki" : "Perempuan" }}</div>
                  </div>
                  <span v-if="f.juaraRank" class="text-[10px] font-extrabold text-[#15803D]">{{ juaraLabel(katId, f.juaraRank, true) }}</span>
                </div>
              </div>
            </template>
          </div>
        </div>
      </div>

      <!-- CTA Daftar -->
      <div v-if="l.status === 'aktif' && l.pendaftaranDibuka !== false" id="cta-daftar" class="mt-5">
        <div class="bg-gradient-to-br from-[#FCE0E0] to-white border-2 border-[#E11D1D] rounded-2xl p-4 text-center">
          <div class="text-[14px] font-bold text-[#9D1010] mb-1">Siap ikut lomba ini? 🎉</div>
          <div class="text-[12px] text-[#6B7280] mb-3">Gratis, tanpa login, daftar dalam 1 menit</div>
          <NuxtLink :to="`/lomba/daftar/${l.id}`" class="btn btn-primary btn-block anim-pulse-glow">
            <i class="fas fa-pen-to-square" /> Daftar Sekarang
          </NuxtLink>
        </div>
      </div>
      <div v-else-if="l.pendaftaranDibuka === false" class="notice notice-warn mt-5">
        <i class="fas fa-lock" />
        <div>
          <strong>Pendaftaran sudah ditutup.</strong>
          <p class="m-0 text-[11px] opacity-80">Coba lihat lomba lain yang masih buka.</p>
        </div>
      </div>
    </main>
  </div>
</template>
